[package]
name = "mae"
version = "0.1.1"
edition = "2021"
license = "MIT OR Apache-2.0"
description = "Mae is used to standardize and streamline the creation of micro-services."
homepage = "https://statbook.io"
readme = "./README.md"
repository = "https://github.com/MrCartaaa/mae"

[dependencies]
domain_macro = {path = "./repo_macro"}
chrono = "0.4.41"
serde_json = "1.0.140"

[dev-dependencies]
anyhow = "1.0.98"
