[package]
name = "domain"
version = "0.1.0"
edition = "2024"
license = "MIT OR Apache-2.0"

[lib]
proc-macro=true


[dependencies]
chrono = "0.4.41"
quote = "1.0.40"
serde_json = "1.0.140"
syn = { version = "2.0.104", features = ["extra-traits"] }
